before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

image: docker.causeex.com/dart/sbt-builder:latest

build-project:
  stage: build
  script:
    - make docker-build

publish-artifact:
  stage: deploy
  only:
    - master
    - tags
  script:
    - make docker-push
